### ISSUE TITLE
Scripts  viessmann-mqtt-gateway and viessmann-mqtt-sub crash after some hours of utilization

### ISSUE THREAD

**Issue by tfagart** [mqu/viessmann-mqtt#3]
Hello,

Thanks for your piece of software, but I've noticed that after some hour of utilization, I got the following error in viessmann-mqtt-gateway.log

13:35:21 publishing new value : /data/temp/gaz=40
/var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/mqtt/packet.rb:283:in `read_byte': Failed to read byte from socket (MQTT::ProtocolException)
        from /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/mqtt/packet.rb:31:in `read'
        from /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/mqtt/client.rb:481:in `receive_packet'
        from /var/lib/gems/2.3.0/gems/mqtt-0.5.0/lib/mqtt/client.rb:302:in `block in connect'

And this one in viessmann-mqtt-sub.log
topic=v1/home/objects/viessman/data/settings/power/mode/1
received v1/home/objects/viessman/data/settings/power/mode=1
on
script exiting ... ; time: 29/05/2018 13:35

Thanks for your help

Regards

Thomas

**Comment by mqu** [comment]
hello Thomas, I am discovering your message. I am going to investigate on this problem soon.

**Comment by mqu** [comment]
What I  know now is that USB connection some time break and there is now way to reconnect to Viessmann heating device, except by rebooting computer.

**Comment by mqu** [comment]
I have exactly same error when I stop mosquitto server. I will try to write disconnection to mosquitto server and try to reconnect. Best regards.

**Comment by mqu** [comment]
hello Thomas. I have pushed a new commit with exception handling. You may issue a git pull to download latest update.
